# Generated by Django 5.2.6 on 2025-11-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='RTSP URL or camera index', max_length=255)),
                ('stream_type', models.CharField(choices=[('rtsp', 'RTSP Stream'), ('http', 'HTTP Stream'), ('local', 'Local Camera')], default='rtsp', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
