# Generated by Django 5.2.6 on 2025-11-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(help_text='RTSP URL (rtsp://...), HTTP URL (http://...), or camera index (0, 1, 2...)', max_length=255),
        ),
    ]
