# Generated by Django 5.2.6 on 2025-11-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
